function varargout = aeroicon(varargin)
varargout{1}=[];
varargout{2}=[];
varargout{3}=[];
varargout{4}=[];
varargout{5}=[];
varargout{6}=[];
varargout{7}=[];
varargout{8}=[];
varargout{9}=[];
varargout{10}=[];
varargout{11}=[];
